//! Frame-loop integration test — build a small deterministic SimState,
//! run `simulate_action_phase`, and assert final HP / SP / mobile-count
//! match values derived from running the Python reference sim on the
//! same input.
//!
//! Expected values were generated by running `algos/athena/sim/pysim.py`'s
//! `simulate_action_phase` on the same initial state (see inline comment
//! in each assertion for the Python-derivation script).

use std::path::PathBuf;

use sim_rs::config::{
    SimConfig, IDX_SCOUT, IDX_SUPPORT, IDX_TURRET,
};
use sim_rs::map::{EDGE_TOP_LEFT, EDGE_TOP_RIGHT};
use sim_rs::sim::simulate_action_phase;
use sim_rs::state::{Mobile, PlayerStats, SimState, Structure};

fn snapshot_path() -> PathBuf {
    let mut p = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    p.push("..");
    p.push("data");
    p.push("citadel_config_snapshot.json");
    p
}

/// Scenario (derived via Python script — see header):
///
/// * p2 upgraded turrets at (13,14), (14,14) — HP 100 each
/// * p2 upgraded support at (13,17) — HP 40
/// * p1 scout at (13,0) → target EDGE_TOP_RIGHT — HP 15
/// * p1 scout at (14,0) → target EDGE_TOP_LEFT  — HP 15
///
/// Expected post-action-phase state (Python reference):
///   frame_count = 29
///   p1.hp = 40.0, p1.sp = 10.0 (2 breaches × 1.0 each)
///   p2.hp = 38.0 (2 scouts breached, each dealing 1 HP)
///   n_mobiles_alive = 0 (both breached → destroyed on-frame)
///   n_structures_alive = 3 (no structures killed)
#[test]
fn two_scouts_breach_p2_edge() {
    let cfg = SimConfig::load(&snapshot_path()).expect("config");

    let mut state = SimState::new(5);
    state.p1 = PlayerStats { hp: 40.0, sp: 8.0, mp: 1.0 };
    state.p2 = PlayerStats { hp: 40.0, sp: 8.0, mp: 1.0 };

    // Insertion order of structures defines engine `gameObjects` iteration —
    // must match Python reference, which inserted turrets first then support.
    state.structures.insert(
        (13, 14),
        Structure {
            xy: (13, 14),
            type_idx: IDX_TURRET,
            upgraded: true,
            hp: 100.0,
            uid: 100,
            player: 2,
            turn_start_removal: None,
            shielded_already: Vec::new(),
        },
    );
    state.structures.insert(
        (14, 14),
        Structure {
            xy: (14, 14),
            type_idx: IDX_TURRET,
            upgraded: true,
            hp: 100.0,
            uid: 101,
            player: 2,
            turn_start_removal: None,
            shielded_already: Vec::new(),
        },
    );
    state.structures.insert(
        (13, 17),
        Structure {
            xy: (13, 17),
            type_idx: IDX_SUPPORT,
            upgraded: true,
            hp: 40.0,
            uid: 102,
            player: 2,
            turn_start_removal: None,
            shielded_already: Vec::new(),
        },
    );

    // Mobiles: two p1 scouts heading for p2 edge.
    state.mobiles.push(Mobile {
        xy: (13, 0),
        type_idx: IDX_SCOUT,
        hp: 15.0,
        shield: 0.0,
        uid: 200,
        player: 1,
        spawn_xy: (13, 0),
        target_edge: EDGE_TOP_RIGHT,
        steps_taken: 0,
        move_buildup: 0.0,
        last_move: 0,
        finished_navigating: false,
        reached_target: false,
        breached: false
    });
    state.mobiles.push(Mobile {
        xy: (14, 0),
        type_idx: IDX_SCOUT,
        hp: 15.0,
        shield: 0.0,
        uid: 201,
        player: 1,
        spawn_xy: (14, 0),
        target_edge: EDGE_TOP_LEFT,
        steps_taken: 0,
        move_buildup: 0.0,
        last_move: 0,
        finished_navigating: false,
        reached_target: false,
        breached: false
    });

    let result = simulate_action_phase(&mut state, &cfg, 200);

    // Engine citation: GameMain.runLoop:268-318 — termination at walkersAlive=false.
    assert_eq!(
        result.frame_count, 29,
        "frame_count must match Python reference (GameMain.runLoop)"
    );

    // Player HP — p1 breaches dealt 2×1.0 HP damage to p2.
    assert_eq!(
        result.final_state.p1.hp, 40.0,
        "p1 HP untouched — no p2 mobiles in this scenario"
    );
    assert_eq!(
        result.final_state.p2.hp, 38.0,
        "p2 HP should drop 2 from 2 scout breaches"
    );

    // SP refunds — metalForBreach=1 per scout breach.
    assert_eq!(
        result.final_state.p1.sp, 10.0,
        "p1 SP = 8 + 2 × metalForBreach(1) = 10"
    );
    assert_eq!(
        result.final_state.p2.sp, 8.0,
        "p2 SP untouched (no deploys, no breaches)"
    );

    // Damage totals in ActionResult.
    assert_eq!(result.p1_damage_dealt, 2.0, "p1 dealt 2 HP to p2");
    assert_eq!(result.p2_damage_dealt, 0.0, "p2 dealt 0 HP to p1");

    // Mobiles: both breached → destroyed on the breach frame.
    assert_eq!(
        result.final_state.mobiles.len(),
        0,
        "both scouts breached → cleared"
    );

    // Structures: all three p2 structures survive.
    assert_eq!(
        result.final_state.structures.len(),
        3,
        "no structures damaged below 0 HP"
    );
}
